### ISSUE TITLE
装了这个主题后全站500错误。。

### ISSUE THREAD

**Issue by lwl12** [DIYgod/Amativeness#1]
=。=挺漂亮的，装不了

**Comment by DIYgod** [comment]
那个。。我是从我博客直接复制过来的。。我博客用的好好的，所以目测是有哪里的链接需要改一下，放假我再研究研究。。。

**Comment by lwl12** [comment]
谢喽~哈哈，或许是我服务器问题呢
还有，现在在放假

**Comment by DIYgod** [comment]
如果解决了麻烦告诉我一下哦|´・ω・)ノ

**Comment by lwl12** [comment]
表示不打算试了|´・ω・)ノubuntu小白

**Comment by lwl12** [comment]
DIYgod closed this on 30 Mar 2015

**Comment by lwl12** [comment]
🌚黑历史

**Comment by gggoe** [comment]
<s>可远观，不可亵玩</s>
